require('coffee-script');
require 'colors'

module.exports = log =
  name: 'default'
  log:     (str...) -> console.log '[' + log.name.magenta + ']', str...
  debug:   (str...) -> console.log '[' + log.name.magenta, '-', 'debug'.green + ']', str...
  info:    (str...) -> console.log '[' + log.name.magenta, '-', 'info'.white + ']', str...
  warn:    (str...) -> console.log '[' + log.name.magenta, '-', 'warn'.yellow + ']', str...
  error:   (str...) -> console.log '[' + log.name.magenta, '-', 'error'.red + ']', str...
  setName: (str)    -> log.name = str
